### ISSUE TITLE
Give a cool background animation

### ISSUE THREAD

**Issue by manaswinidas** [manaswinidas/Notes#1]
Write text with animation: Welcome to Notes, Font size, and style of your choice.

**Comment by Pritom14** [comment]
Refractor : #2 
Please review

**Comment by Pritom14** [comment]
![1yc1v9](https://user-images.githubusercontent.com/16569570/32088667-a87ccd52-bb02-11e7-84b1-5de64dd28c12.gif)

**Comment by manaswinidas** [comment]
Closed via #2
